#!/bin/sh
cd $HOME/go/src/gitlab.com/zwhitchcox
echo 3
PROJ="$1"
set -- $(stty size) # $1 = rows $2 = columns
echo 6
tmux -2 new-session -d -s "$PROJ" -x "$2" -y "$(($1 - 1))"
echo 8
echo $PROJ
tmux split-window -t "$PROJ" -v
echo 11
tmux resize-pane -t "$PROJ" -y "10"
tmux select-pane -t "1"
tmux send-keys "cd $PROJ"
tmux send-keys "Enter"
tmux send-keys "vim"
tmux send-keys "Enter"
tmux select-pane -t "2"
tmux send-keys "cd $PROJ"
tmux send-keys "Enter"
tmux send-keys "yarn dev:up"
tmux send-keys "Enter"
tmux select-pane -t "1"
tmux new-window
tmux send-keys "cd $PROJ"
tmux send-keys "Enter"
tmux previous-window
echo 27
tmux attach -t "$PROJ"
