#!/bin/bash
cp -r ~/.bashrc ~/dotfiles
cp -r ~/.vimrc ~/dotfiles
cp -r ~/.tmux.conf ~/dotfiles
cp -r ~/.gitconfig ~/dotfiles
cp -r ~/.snippets ~/dotfiles
cp -r ~/.aliases ~/dotfiles
cp -r ~/.bin ~/dotfiles
$(cd ~/dotfiles && gitpush update)
